# docker/Dockerfile-app
FROM debian:12.9

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    python3 \
    python3-pip \
    doxygen \
    graphviz \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
CMD ["bash"]
